[versions]
appauth = "0.11.1"
#gson = "2.13.2"
kmmCrypto = "2.0.1"
koinAndroidxCompose = "4.1.1"
kotlin = "2.3.0"
compose = "1.10.0"
agp = "8.13.2"
androidx-activityCompose = "1.12.2"
androidx-uiTest = "1.10.0"
kotlinxCoroutinesCore = "1.10.2"
material3Version = "1.10.0-alpha05"
maven-publish = "0.35.0"
ktor = "3.3.3"
startupRuntime = "1.2.0"
[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
androidx-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
appauth = { module = "net.openid:appauth", version.ref = "appauth" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
#gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jetbrains-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3Version" }
kmm-crypto = { module = "io.github.the-best-is-best:kmm-crypto", version.ref = "kmmCrypto" }

koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }


[plugins]

native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish = {id = "com.vanniktech.maven.publish" , version.ref = "maven-publish"}
